version: '3.8'

services:
  webrtc-contrib:
    build: .
    container_name: webrtc-contrib-app
    ports:
      - "3030:3030"
    volumes:
      - ./recordings:/usr/src/app/recordings
    restart: unless-stopped