version: '3.8'

services:
  app:
    build: .
    container_name: webrtc-radio-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # No volumes for code; rebuild for changes
