version: '3.3'

services:
  app:
    build: .
    container_name: webrtc-radio-app
    ports:
      - "3030:3030"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # No volumes for code; rebuild for changes
